plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'lib/osc_proxy/config.rb'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - '*.gemspec'
    - 'lib/osc_proxy/config.rb'

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'test/**/*'
    - 'lib/osc_proxy/config.rb'

Metrics/CyclomaticComplexity:
  Max: 10
